// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMg9pBjxV8F4A0v4ocIvEp0qOOsPceIVk',
    appId: '1:528355411283:web:28324debccbe0652fa4da6',
    messagingSenderId: '528355411283',
    projectId: 'cric-rec',
    authDomain: 'cric-rec.firebaseapp.com',
    storageBucket: 'cric-rec.firebasestorage.app',
    measurementId: 'G-M9TSEBHC29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcyMPVvEshyKTGxVpSX3GilKGaIlxwD7I',
    appId: '1:528355411283:android:6af81f77b0bcea46fa4da6',
    messagingSenderId: '528355411283',
    projectId: 'cric-rec',
    storageBucket: 'cric-rec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZF2Maod-dzT7ZG0UdE8Z7-I8dE6ST-fQ',
    appId: '1:528355411283:ios:a1b6ba232b682c0cfa4da6',
    messagingSenderId: '528355411283',
    projectId: 'cric-rec',
    storageBucket: 'cric-rec.firebasestorage.app',
    iosBundleId: 'com.example.cricRec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZF2Maod-dzT7ZG0UdE8Z7-I8dE6ST-fQ',
    appId: '1:528355411283:ios:a1b6ba232b682c0cfa4da6',
    messagingSenderId: '528355411283',
    projectId: 'cric-rec',
    storageBucket: 'cric-rec.firebasestorage.app',
    iosBundleId: 'com.example.cricRec',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMg9pBjxV8F4A0v4ocIvEp0qOOsPceIVk',
    appId: '1:528355411283:web:9144a2894f3ca464fa4da6',
    messagingSenderId: '528355411283',
    projectId: 'cric-rec',
    authDomain: 'cric-rec.firebaseapp.com',
    storageBucket: 'cric-rec.firebasestorage.app',
    measurementId: 'G-PE4FG6FGDC',
  );
}
